### ISSUE TITLE
BPF object creation errors after execution of eaudit.py

### ISSUE THREAD

**Issue by JacquesJurado** [ugswork/eaudit#1]
Hi to all,
i am currently working on execute the eaudit program on debian 12 (bookworm) with 4.19 kernel. After i've installed bcc according your provided bcc-install.sh script the execution of eauditd.py runs into some following errors:

`root@localhost:/data/local/tmp/eaudit-master# time python3 eauditd.py`

`10 warnings and 20 errors generated.
Traceback (most recent call last):
  File "/data/local/tmp/eaudit-master/eauditd.py", line 264, in <module>
    b = BPF(text=src);
        ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/bcc-0.28.0+cab1f40a-py3.11.egg/bcc/__init__.py", line 479, in __init__`

`/virtual/main.c:913:24: error: incomplete definition of type 'struct tracepoint__syscalls__sys_enter_open'
   store_open_args(args->__syscall_nr, args->filename, AT_FDCWD, 
                   ~~~~^
/virtual/main.c:913:44: error: incomplete definition of type 'struct tracepoint__syscalls__sys_enter_open'
   store_open_args(args->__syscall_nr, args->filename, AT_FDCWD, 
                                       ~~~~^`

It seems that the program has some definition errors with the struct `args` in the `eauditk.c` file. Can you please help me?
Thanks!

**Comment by profsekar** [comment]
The kernel could be too old, or more likely, it may not be compiled with
the right options. Please check the bcc documentation on the requirements
on the kernel. Your best bet is to check if bcc works on your system --
they have sample code to try out.
-- Sekar
