### ISSUE TITLE
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b

### ISSUE THREAD

**Issue by tdnavarrom** [ugswork/eaudit#3]
After installing bcc with the script provided using ubuntu 22.0.4 I am getting this error when using the ./ecapd as root:

``` bash
Traceback (most recent call last):
  File "/home/vagrant/eaudit/eauditd.py", line 30, in <module>
    from bcc import BPF
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 27, in <module>
    from .libbcc import lib, bcc_symbol, bcc_symbol_option, bcc_stacktrace_build_id, _SYM_CB_TYPE
  File "/usr/lib/python3/dist-packages/bcc/libbcc.py", line 20, in <module>
    lib.bpf_module_create_b.restype = ct.c_void_p
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libbcc.so.0: undefined symbol: bpf_module_create_b
Command exited with non-zero status 1
0.09user 0.02system 0:00.12elapsed 100%CPU (0avgtext+0avgdata 67044maxresident)k
0inputs+0outputs (0major+5605minor)pagefaults 0swaps
```

**Comment by profsekar** [comment]
The most likely reason is that bcc was not properly installed. Make sure that you install from source. If you install using other methods (they have binary packages available), it does not work. Secondly, bcc comes with several example programs that you should try running. Once bcc is properly installed, eaudit will  work fine.
